### PR TITLE
Support us_bank_account PaymentMethods (OG-2313)

### PR DESCRIPTION
**Pull request by anginblu**
## Summary

The PaymentMethods endpoints in the stub always returned a card-shaped fixture, regardless of the requested `type`. With the GiveCampus app's ACH migration (legacy Sources API → PaymentMethods API for US bank accounts, see OG-2285), code paths that list/retrieve a saved bank account now hit `PaymentMethod.list(type: "us_bank_account")` and read the `us_bank_account` hash — which the stub never returned, so the real Stripe gem raised `NoMethodError` on the missing attribute.

This PR adds `us_bank_account` fidelity across the full PaymentMethod lifecycle, following the fork's existing conventions (type-aware fixtures + id sentinels):

- **create** (`POST /v1/payment_methods`) and **list** (`GET /v1/payment_methods`) branch on the request `type` param → return the `us_bank_account` fixture when `type=us_bank_account`, otherwise the existing card fixture.
- **retrieve / attach / detach** branch on a `pm_usba_` id sentinel → return the `us_bank_account` variant of the relevant fixture, otherwise the card fixture.

## Changes

- Five new fixtures: `create`, `retrieve`, `list`, `attach`, `detach` us_bank_account PaymentMethod variants (modeled on the real Stripe `us_bank_account` object — account_holder_type, account_type, bank_name, fingerprint, last4, routing_number, networks).
- `payment_method_fixture_for(id, default)` helper that maps a default (card) fixture name to its us_bank_account variant for `pm_usba_`-prefixed ids.
- New spec `spec/fake_stripe/requests/payment_method_us_bank_account_spec.rb` covering all five operations (8 examples).

## Testing

- New spec: 8 examples, 0 failures.
- Full suite: the only 3 failures are pre-existing on `main` (Stripe gem version drift — `Stripe::Recipient` removed, etc.), unrelated to this change.

## Follow-up

Once merged, bump the `fake_stripe` revision in `givecampus/givecampus`'s `Gemfile.lock` (OG-2313 AC).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by anginblu** [comment]
### Validated end-to-end against givecampus

Confirmed this change is the real fix for the ACH (Sources → PaymentMethods) test gap, not just belt-and-suspenders:

- Pointed `givecampus`'s `Gemfile` at this branch (`85dabdc`) and **removed** the defensive `respond_to?(:us_bank_account)` guard that OG-2285 added to `StripeService#get_bank_account_sources`.
- Ran the request specs that render a saved bank account through the default FakeStripe path (`recurring_subscriptions/show`, `update`, `permissions`): **84/85 passing**. The single miss passes in isolation — it's pre-existing test-ordering pollution in a hand-stubbed example, unrelated to this change.
- On the currently-pinned gem (`52e08a5`, card-only fixture) those same specs all crash with `NoMethodError: undefined method 'us_bank_account'`.

So with this PR the stub returns a properly-shaped `us_bank_account` PaymentMethod and the app's bank-account read paths work without relying on the guard.

Follow-up: once merged, bump the `fake_stripe` revision in `givecampus/givecampus`'s `Gemfile.lock` (OG-2313 AC #3).

**Comment by seisen77** [comment]
Looks like thoughtbot has [deprecated this gem](https://github.com/givecampus/fake_stripe/commit/89937169289e7a551edbe14b4336ca8fd551c0ea) - did we consider doing something similar?

**Comment by anginblu** [comment]
@seisen77 I think that is a bigger decision. we have so many specs relying on this gem; and we've been separately maintaining this gem because it's no longer supported.

**Review by alejandro-givecampus — APPROVED** [review]

**Comment by alejandro-givecampus** [comment]
It also looks like the gem thoughtbot recommends is more out of date with stripe than we are 😢
